spring:
  application:
    name: servicio-reservas
server:
  port: 8001
  servlet:
    context-path: /reservas
eureka:
 client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    