spring:
  application:
    name: servicio-hoteles
server:
  port: 8002
  servlet:
    context-path: /viajes
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka